{
	"id": "ALSA-2022:0643",
	"advisories": [
		{
			"content": {
				"id": "ALSA-2022:0643",
				"title": "Important: python-pillow security update",
				"description": "The python-pillow packages contain a Python image processing library that provides extensive file format support, an efficient internal representation, and powerful image-processing capabilities.\n\nSecurity Fix(es):\n\n* python-pillow: PIL.ImageMath.eval allows evaluation of arbitrary expressions (CVE-2022-22817)\n\n* python-pillow: buffer over-read during initialization of ImagePath.Path in path_getbbox() in path.c (CVE-2022-22816)\n\nFor more details about the security issue(s), including the impact, a CVSS score, acknowledgments, and other related information, refer to the CVE page(s) listed in the References section.",
				"severity": [
					{
						"type": "vendor",
						"source": "errata.almalinux.org",
						"vendor": "Important"
					}
				],
				"references": [
					{
						"source": "errata.almalinux.org",
						"url": "https://errata.almalinux.org/8/ALSA-2022-0643.html"
					},
					{
						"source": "errata.almalinux.org",
						"url": "https://vulners.com/cve/CVE-2022-22815"
					},
					{
						"source": "errata.almalinux.org",
						"url": "https://vulners.com/cve/CVE-2022-22816"
					},
					{
						"source": "errata.almalinux.org",
						"url": "https://vulners.com/cve/CVE-2022-22817"
					}
				],
				"published": "2022-02-22T17:25:31Z",
				"modified": "2022-02-23T13:24:49Z"
			},
			"ecosystems": [
				"alma:8"
			]
		}
	],
	"vulnerabilities": [
		{
			"content": {
				"id": "CVE-2022-22815",
				"references": [
					{
						"source": "errata.almalinux.org",
						"url": "https://vulners.com/cve/CVE-2022-22815"
					}
				]
			},
			"ecosystems": [
				"alma:8"
			]
		},
		{
			"content": {
				"id": "CVE-2022-22816",
				"references": [
					{
						"source": "errata.almalinux.org",
						"url": "https://vulners.com/cve/CVE-2022-22816"
					}
				]
			},
			"ecosystems": [
				"alma:8"
			]
		},
		{
			"content": {
				"id": "CVE-2022-22817",
				"references": [
					{
						"source": "errata.almalinux.org",
						"url": "https://vulners.com/cve/CVE-2022-22817"
					}
				]
			},
			"ecosystems": [
				"alma:8"
			]
		}
	],
	"detection": [
		{
			"ecosystem": "alma:8",
			"criteria": {
				"operator": "OR",
				"criterions": [
					{
						"vulnerable": true,
						"package": {
							"name": "python3-pillow",
							"architectures": [
								"aarch64",
								"i686",
								"ppc64le",
								"x86_64"
							]
						},
						"affected": {
							"type": "rpm",
							"range": [
								{
									"lt": "0:5.1.1-18.el8_5"
								}
							],
							"fixed": [
								"0:5.1.1-18.el8_5"
							]
						}
					},
					{
						"vulnerable": true,
						"package": {
							"name": "python3-pillow-devel",
							"architectures": [
								"aarch64",
								"i686",
								"ppc64le",
								"x86_64"
							]
						},
						"affected": {
							"type": "rpm",
							"range": [
								{
									"lt": "0:5.1.1-18.el8_5"
								}
							],
							"fixed": [
								"0:5.1.1-18.el8_5"
							]
						}
					},
					{
						"vulnerable": true,
						"package": {
							"name": "python3-pillow-doc",
							"architectures": [
								"noarch"
							]
						},
						"affected": {
							"type": "rpm",
							"range": [
								{
									"lt": "0:5.1.1-18.el8_5"
								}
							],
							"fixed": [
								"0:5.1.1-18.el8_5"
							]
						}
					},
					{
						"vulnerable": true,
						"package": {
							"name": "python3-pillow-tk",
							"architectures": [
								"aarch64",
								"ppc64le",
								"x86_64"
							]
						},
						"affected": {
							"type": "rpm",
							"range": [
								{
									"lt": "0:5.1.1-18.el8_5"
								}
							],
							"fixed": [
								"0:5.1.1-18.el8_5"
							]
						}
					}
				]
			}
		}
	],
	"data_source": {
		"id": "alma-errata",
		"raws": [
			"vuls-data-raw-alma-errata/8/2022/ALSA-2022:0643.json"
		]
	}
}
